
CREATE SERVICE "ram" TYPE 'JSON' AUTHORIZATION OFF USER "DBA" URL ON METHODS 'GET' AS call proc_ram();
CREATE SERVICE "processeurs" TYPE 'JSON' AUTHORIZATION OFF USER "DBA" URL ON METHODS 'GET' AS call dba.proc_processeurs();
CREATE SERVICE "disqueDur" TYPE 'JSON' AUTHORIZATION OFF USER "DBA" URL ON METHODS 'GET' AS call proc_DisqueDur();
CREATE SERVICE "carteMere" TYPE 'JSON' AUTHORIZATION OFF USER "DBA" URL ON METHODS 'GET' AS call proc_CM();
CREATE SERVICE "carteGraphique" TYPE 'JSON' AUTHORIZATION OFF USER "DBA" URL ON METHODS 'GET' AS call proc_CarteGraphique();
CREATE SERVICE "boitier" TYPE 'JSON' AUTHORIZATION OFF USER "DBA" URL ON METHODS 'GET' AS call proc_boitier();

